const data=[
    {
        id:1,
        name:"Agra",
        info:"Agra is a city on the banks of the Yamuna river in the Indian state of Uttar Pradesh, about 230 kilometres (140 mi) south-east of the national capital Delhi and 330 km west of the state capital Lucknow. With a population of roughly 1.6 million, Agra is the fourth-most populous city in Uttar Pradesh and twenty-third most populous city in India.[10]",
        img:"https://tse3.mm.bing.net/th?id=OIP.IOK9HQQaVocu8_SA8GObagHaFP&pid=Api&P=0&h=180",
        price:14000,
    },
    {
        id:1,
        name:"Mathura",
        info:"Mathura is a city and the administrative headquarters of Mathura district in the Indian state of Uttar Pradesh. It is located approximately 57.6 kilometres (35.8 mi) north of Agra, and 146 kilometres (91 mi) south-east of Delhi; about 14.5 kilometres (9.0 mi) from the town of Vrindavan, and 22 kilometres (14 mi) from Govardhan. In ancient times, Mathura was an economic hub, located at the junction of important caravan routes. The 2011 Census of India estimated the population of Mathura at 441,89",
        img:"https://blog.savaari.com/wp-content/uploads/2021/01/indian-temple-4782312_1920-1024x683.jpg",
        price:15000,
    },
    {
        id:1,
        name:"Delhi",
        info:"Delhi,officially the National Capital Territory (NCT) of Delhi, is a city and a union territory of India containing New Delhi, the capital of India. Straddling the Yamuna river, primarily its western or right bank, Delhi shares borders with the state of Uttar Pradesh in the east and with the state of Haryana in the remaining directions. The NCT covers an area of 1,484 square kilometres (573 sq mi).[2] According to the 2011 census, Delhi's city proper population was over 11 million,[3][11] while the NCT's population was about 16.8 million.[4] Delhi's urban agglomeration, which includes the satellite cities Ghaziabad, Faridabad, Gurgaon and Noida in an area known as the National Capital Region (NCR), has an estimated population of over 28 million, making it the largest metropolitan area in India and the second-largest in the world (after Tokyo).[5]",
        img:"https://tse1.mm.bing.net/th?id=OIP.szidbmHyLuIVSqTtBrXgugHaE7&pid=Api&P=0&h=180",
        price:20000,
    },
    {
        id:1,
        name:"Mumbai",
        info:"Mumbai also known as Bombay the official name until 1995 is the capital city of the Indian state of Maharashtra. Mumbai is the de facto financial centre and the most populous city of India with an estimated city proper population of 12.5 million (1.25 crore).[18] Mumbai is the centre of the Mumbai Metropolitan Region, the sixth most populous metropolitan area in the world with a population of over 23 million (2.3 crore) living under the Brihanmumbai Municipal Corporation.[19] Mumbai lies on the Konkan coast on the west coast of India and has a deep natural harbour. In 2008, Mumbai was named an alpha world city.[20][21]",
        img:"https://i.pinimg.com/originals/a1/6c/60/a16c603829b603f316c0b666c5ee1a75.jpg",
        price:55000,
    },
    {
        id:1,
        name:"Kolkata",
        info:"kolkata  also known as Calcutta which was the official name until 2001) is the capital and largest city of the Indian state of West Bengal. It is on the eastern bank of the Hooghly River 80 km (50 mi) west of the border with Bangladesh. It is the primary business, commercial, and financial hub of Eastern India and the main port of communication for North-East India.[14",
        img:"https://static2.tripoto.com/media/transfer/img/OgData/1500874108_victoria_memorial_hall_kolkata.jpg",
        price:30000,
    },
    {
        id:1,
        name:"Chennai",
        info:"Chennai,formerly known as Madras,[A] is the capital city of Tamil Nadu, the southernmost Indian state. It is the state's primate city both in area and population and is located on the Coromandel Coast of the Bay of Bengal. According to the 2011 Indian census, Chennai is the sixth-most populous city in India and forms the fourth-most populous urban agglomeration. Incorporated in 1866, the Greater Chennai Corporation is the oldest municipal corporation of India and the second oldest in the world after London.",
        img:"https://content.skyscnr.com/6444159c8f0ec14c96012de8a2502245/eyeem-26693940-86115263.jpg",
        price:24000,
    },
    {
        id:1,
        name:"Hyderabad",
        info:"Hyderabad is the capital and largest city of the Indian state of Telangana. It occupies 650 km2 (250 sq mi) on the Deccan Plateau along the banks of the Musi River, in the northern part of Southern India. With an average altitude of 542 m (1,778 ft), much of Hyderabad is situated on hilly terrain around artificial lakes, including the Hussain Sagar lake, predating the city's founding, in the north of the city centre.",
        img:"http://media.cntraveller.in/wp-content/uploads/2014/02/Hyderabad3-Alamy-D9K7KC.jpg",
        price:48000,
    },
    {
        id:1,
        name:"Manali",
        info:"Manali is a town, near Kullu town in Kullu district in the Indian state of Himachal Pradesh.[2] It is situated in the northern end of the Kullu Valley, formed by the Beas River. The town is located in the Kullu district, approximately 270 kilometres (170 mi) north of the state capital of Shimla and 544 kilometres (338 mi) northeast of the national capital of New Delhi.",
        img:"https://tse2.mm.bing.net/th?id=OIP.YucvyV2zVkqqtsxyu2IrzQELDp&pid=Api&P=0&h=180",
        price:25000,
    },
    {
        id:1,
        name:"Kashmir",
        info:"Kashmir is the northernmost geographical region of the Indian subcontinent. Until the mid-19th century, the term  denoted only the Kashmir Valley between the Great Himalayas and the Pir Panjal Range. Today, the term encompasses a larger area that includes the India-administered territories of Jammu and Kashmir and Ladakh, the Pakistan-administered territories of Azad Kashmir and Gilgit-Baltistan, and the Chinese-administered territories of Aksai Chin and the Trans-Karakoram Tract",
        img:"https://wallpapercave.com/wp/wp2678269.jpg",
        price:45000,
    }
]